// <auto-generated>
//   此文件由 ResAddressGenerator 自动生成，请勿手动修改。
//   GameRes 下资源增删改时会自动更新；也可手动运行菜单 Tools/Awen/生成资源地址常量。
// </auto-generated>

/// <summary>GameRes 资源地址常量。用法：ResourceManager.Instance.LoadAsync&lt;T&gt;(ResAddress.Xxx)。</summary>
public static class ResAddress
{
    /// <summary>Art/UI/Fonts/MSYH  ←  Assets/GameRes/Art/UI/Fonts/MSYH.TTC</summary>
    public const string Art_UI_Fonts_MSYH = "Art/UI/Fonts/MSYH";
    /// <summary>Art/UI/Fonts/MSYH SDF  ←  Assets/GameRes/Art/UI/Fonts/MSYH SDF.asset</summary>
    public const string Art_UI_Fonts_MSYH_SDF = "Art/UI/Fonts/MSYH SDF";
    /// <summary>Art/UI/Fonts/MSYHBD  ←  Assets/GameRes/Art/UI/Fonts/MSYHBD.TTC</summary>
    public const string Art_UI_Fonts_MSYHBD = "Art/UI/Fonts/MSYHBD";
    /// <summary>Art/UI/Fonts/MSYHBD SDF  ←  Assets/GameRes/Art/UI/Fonts/MSYHBD SDF.asset</summary>
    public const string Art_UI_Fonts_MSYHBD_SDF = "Art/UI/Fonts/MSYHBD SDF";
    /// <summary>Art/UI/Fonts/MSYHL  ←  Assets/GameRes/Art/UI/Fonts/MSYHL.TTC</summary>
    public const string Art_UI_Fonts_MSYHL = "Art/UI/Fonts/MSYHL";
    /// <summary>Art/UI/Fonts/MSYHL SDF  ←  Assets/GameRes/Art/UI/Fonts/MSYHL SDF.asset</summary>
    public const string Art_UI_Fonts_MSYHL_SDF = "Art/UI/Fonts/MSYHL SDF";
    /// <summary>Prefabs/Audio/SfxPlayer  ←  Assets/GameRes/Prefabs/Audio/SfxPlayer.prefab</summary>
    public const string Prefabs_Audio_SfxPlayer = "Prefabs/Audio/SfxPlayer";
    /// <summary>README  ←  Assets/GameRes/README.txt</summary>
    public const string README = "README";
}
