using System.Collections.Generic;
using System.IO;
using System.Text;
using UnityEditor;
using UnityEngine;
using YooAsset.Editor;

namespace GamePrototype.Editor {
  /// <summary>
  /// 扫描 GameRes 下所有被 YooAsset 收集的资源，生成强类型地址常量到 <c>ResAddress.cs</c>，
  /// 这样写 <c>ResAddress.UI_Icons_heart</c> 即可，避免手打字符串、重命名后还能编译期发现。
  ///
  /// 地址由收集器「实际使用的寻址规则实例」计算（而非另写一套逻辑），
  /// 因此生成的常量值与运行时 <c>ResourceManager.LoadAsync</c> 的 location 完全一致。
  ///
  /// 运行方式：
  /// - 自动：GameRes 下资源增删改时由 <see cref="ResAddressAutoGenerator"/> 触发；
  /// - 手动：菜单 <b>Tools/GamePrototype/生成资源地址常量</b>。
  /// </summary>
  public static class ResAddressGenerator {
    const string _packageName = "DefaultPackage";
    const string _outputPath = "Assets/_Code/Core/Resource/ResAddress.cs";
    const string _className = "ResAddress";

    static readonly HashSet<string> _ignoreExt =
        new HashSet<string>(System.StringComparer.OrdinalIgnoreCase) {
          ".cs", ".meta", ".gitkeep", ".asmdef", ".asmref", ".dll", ".js"
        };

    [MenuItem("Tools/GamePrototype/生成资源地址常量", false, 100)]
    public static void Generate() {
      var setting = AssetBundleCollectorSettingData.Setting;
      if (setting == null) {
        Debug.LogWarning("[ResAddress] 找不到收集器配置 AssetBundleCollectorSetting。");
        return;
      }

      var pkg = setting.Packages.Find(p => p.PackageName == _packageName);
      if (pkg == null) {
        Debug.LogWarning($"[ResAddress] 收集器中找不到 Package '{_packageName}'。");
        return;
      }

      // address -> assetPath（SortedDictionary 保证输出顺序稳定，git diff 干净）
      var addressToPath = new SortedDictionary<string, string>(System.StringComparer.Ordinal);

      foreach (var group in pkg.Groups) {
        foreach (var collector in group.Collectors) {
          // 只有 Main 类型的收集器才参与寻址（Static/Depend 不生成地址）
          if (collector.CollectorType != ECollectorType.MainAssetCollector) {
            continue;
          }

          var rule = AssetBundleCollectorSettingData.GetAddressRuleInstance(
              collector.AddressRuleName);
          if (rule == null) {
            Debug.LogWarning($"[ResAddress] 未知寻址规则 '{collector.AddressRuleName}'，跳过。");
            continue;
          }

          foreach (var assetPath in EnumerateAssets(collector.CollectPath)) {
            string address = rule.GetAssetAddress(new AddressRuleData(
                assetPath, collector.CollectPath, group.GroupName, collector.UserData));
            if (string.IsNullOrEmpty(address)) {
              continue;
            }
            addressToPath[address] = assetPath;
          }
        }
      }

      WriteIfChanged(BuildContent(addressToPath), addressToPath.Count);
    }

    static IEnumerable<string> EnumerateAssets(string collectPath) {
      if (AssetDatabase.IsValidFolder(collectPath)) {
        foreach (var guid in AssetDatabase.FindAssets("", new[] { collectPath })) {
          string path = AssetDatabase.GUIDToAssetPath(guid);
          if (AssetDatabase.IsValidFolder(path)) {
            continue;
          }
          if (!IsCollectable(path)) {
            continue;
          }
          yield return path;
        }
      } else if (!string.IsNullOrEmpty(collectPath) && File.Exists(collectPath)) {
        if (IsCollectable(collectPath)) {
          yield return collectPath;
        }
      }
    }

    static bool IsCollectable(string path) {
      string ext = Path.GetExtension(path);
      if (string.IsNullOrEmpty(ext)) {
        return false;  // 无扩展名（含 .gitkeep）不当作可加载资源
      }
      return !_ignoreExt.Contains(ext);
    }

    static string BuildContent(SortedDictionary<string, string> map) {
      var used = new HashSet<string>(System.StringComparer.Ordinal);
      var collisions = new List<string>();
      var body = new StringBuilder();

      foreach (var kv in map) {
        string address = kv.Key;
        string baseName = ToIdentifier(address);
        string name = baseName;
        int n = 2;
        while (!used.Add(name)) {
          name = baseName + "_" + n;
          n++;
        }
        if (name != baseName) {
          collisions.Add($"{address} -> {name}");
        }

        body.AppendLine($"    /// <summary>{address}  ←  {kv.Value}</summary>");
        body.AppendLine($"    public const string {name} = \"{address}\";");
      }

      var sb = new StringBuilder();
      sb.AppendLine("// <auto-generated>");
      sb.AppendLine("//   此文件由 ResAddressGenerator 自动生成，请勿手动修改。");
      sb.AppendLine("//   GameRes 下资源增删改时会自动更新；也可手动运行菜单 Tools/GamePrototype/生成资源地址常量。");
      sb.AppendLine("// </auto-generated>");
      sb.AppendLine();
      sb.AppendLine(
          "/// <summary>GameRes 资源地址常量。用法：ResourceManager.Instance.LoadAsync&lt;T&gt;(ResAddress.Xxx)。</summary>");
      sb.AppendLine($"public static class {_className}");
      sb.AppendLine("{");
      sb.Append(body);
      sb.AppendLine("}");

      if (collisions.Count > 0) {
        Debug.LogWarning(
            "[ResAddress] 常量名冲突（已自动加后缀，建议重命名资源避免歧义）：\n" +
            string.Join("\n", collisions));
      }

      return sb.ToString();
    }

    static string ToIdentifier(string address) {
      var sb = new StringBuilder(address.Length);
      foreach (char c in address) {
        sb.Append(char.IsLetterOrDigit(c) ? c : '_');
      }
      if (sb.Length == 0) {
        return "_";
      }
      if (char.IsDigit(sb[0])) {
        sb.Insert(0, '_');
      }
      return sb.ToString();
    }

    static void WriteIfChanged(string content, int count) {
      string full = Path.GetFullPath(_outputPath);
      string dir = Path.GetDirectoryName(full);
      if (!Directory.Exists(dir)) {
        Directory.CreateDirectory(dir);
      }

      // 内容无变化则不写，避免无谓的重新编译与 git 改动
      if (File.Exists(full) && File.ReadAllText(full) == content) {
        return;
      }

      File.WriteAllText(full, content);
      AssetDatabase.ImportAsset(_outputPath);
      Debug.Log($"[ResAddress] 已生成 {count} 个资源地址常量 -> {_outputPath}");
    }
  }
}
